provides: sys/kdsoap-ws-discovery
type: system
cmake-packages: KDSoapWSDiscoveryClient
platform-packages:
    debian: libkdsoapwsdiscoveryclient-qt6-dev
    devuan: libkdsoapwsdiscoveryclient-qt6-dev
    arch: kdsoap-ws-discovery-client
