sources:
    git:
        ref: origin/${master_branch}
        remotes:
            origin:
                url: ${sonicde_git}/${@basename}.git
                depth: ${sonic_depth}
                fetch: ${@SOLUTION::fetch::origin}
            upstream:
                url: ${kf6_git}/kio.git
                depth: ${upstream_depth}
                fetch: ${@SOLUTION::fetch::upstream}
        config:
            autopick.enabled: 'true'
            autopick.upstream: upstream/master
            autopick.master: origin/${master_branch}
            autopick.tracker: origin/tracking/master
            advice.detachedHead: 'false'
            remote.origin.tagOpt: --no-tags
            remote.upstream.tagOpt: --no-tags
        local-branch: ${master_branch}

master_branch: master

buildsystem: cmake

build-depends:
    - sonicde/sonic-frameworks-cmake-modules

depends:
    - sonicde/sonic-frameworks-app-info
    - sonicde/sonic-frameworks-autocomplete
    - sonicde/sonic-frameworks-bookmarks
    - sonicde/sonic-frameworks-color-scheme
    - sonicde/sonic-frameworks-crash-handler
    - sonicde/sonic-frameworks-data-views
    - sonicde/sonic-frameworks-dbus
    - sonicde/sonic-frameworks-device-integration
    - sonicde/sonic-frameworks-icon-themes
    - sonicde/sonic-frameworks-progress-ui
    - sonicde/sonic-frameworks-windowsystem
