sources:
    git:
        ref: origin/${master_branch}
        remotes:
            origin:
                url: ${sonicde_git}/${@basename}.git
                depth: ${sonic_depth}
                fetch: ${@SOLUTION::fetch::origin}
            upstream:
                url: https://invent.kde.org/system/ksystemlog.git
                depth: ${upstream_depth}
                fetch: ${@SOLUTION::fetch::upstream}
        config:
            autopick.enabled: 'true'
            autopick.upstream: upstream/release/26.04
            autopick.master: origin/${master_branch}
            autopick.tracker: origin/tracking/release-26.04
            advice.detachedHead: 'false'
            remote.origin.tagOpt: --no-tags
            remote.upstream.tagOpt: --no-tags
        local-branch: ${master_branch}

master_branch: master

buildsystem: cmake

build-depends:
    - sonicde/sonic-frameworks-cmake-modules

depends:
    - sonicde/sonic-frameworks-archive
    - sonicde/sonic-frameworks-autocomplete
    - sonicde/sonic-frameworks-core-addons
    - sonicde/sonic-frameworks-crash-handler
    - sonicde/sonic-frameworks-data-views
    - sonicde/sonic-frameworks-doctools
    - sonicde/sonic-frameworks-internationalization
    - sonicde/sonic-frameworks-io
    - sonicde/sonic-frameworks-settings
    - sonicde/sonic-frameworks-text-widgets
    - sonicde/sonic-frameworks-widgets-addons
    - sonicde/sonic-frameworks-xml-gui
