#!/usr/bin/env python3
# SPDX-License-Identifier: CC0-1.0
"""
Generate the CMake superbuild (ExternalProject) from the normalized model.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path


def sanitize_target(name: str) -> str:
    """Generate a stable sanitized CMake target name."""
    return re.sub(r"[^a-zA-Z0-9_]", "_", name)


def generate_cmake(model: dict, out_file: Path) -> None:
    """Generate the SonicDEProjects.cmake file."""
    packages = model["packages"]
    edges = model["edges"]
    install_prefix = model.get("install_prefix", "")
    source_root = model.get("source_root", "")
    build_dir = model.get("build_dir", "")

    lines: list[str] = [
        "# Auto-generated by scripts/generate.py - do not edit",
        f"# Active closure: {len(packages)} packages, {len(edges)} edges",
        "",
        "include(ExternalProject)",
        "",
        f"set(SONICDE_INSTALL_PREFIX \"{install_prefix}\")",
        f"set(SONICDE_SOURCE_ROOT \"{source_root}\")",
        f"set(SONICDE_BUILD_DIR \"{build_dir}\")",
        "",
    ]

    # Build target name mapping
    target_map: dict[str, str] = {}
    for name in packages:
        target_map[name] = sanitize_target(name)

    # Emit one target per active package
    for name in model.get("topo_order", []):
        pkg = packages[name]
        target = target_map[name]

        # System packages: validation target (no-op if no pkg-config)
        if pkg.get("type") == "system":
            lines.append(f"# System validation target: {name}")
            lines.append(f"add_custom_target({target})")
            lines.append(f"message(STATUS \"system dep: {name}\")")
            lines.append("")
            continue

        # No-build packages: no-op dependency target
        if pkg.get("buildsystem") == "none":
            lines.append(f"# No-build target: {name}")
            lines.append(f"add_custom_target({target})")
            lines.append("")
            continue

        # Unsupported build systems should have been rejected during
        # closure validation. Skip them here as a safety net.
        bs = pkg.get("buildsystem", "")
        if bs not in ("cmake", ""):
            lines.append(f"# WARNING: unsupported buildsystem '{bs}' for {name}")
            lines.append("")
            continue

        # CMake ExternalProject
        git = pkg.get("git") or {}
        source_dir = f"{source_root}/{name}"

        # Collect direct prerequisite targets
        prereqs = [target_map[e["prerequisite"]]
                   for e in edges if e["dependent"] == name]
        deps_str = ";".join(prereqs) if prereqs else ""

        # CMake arguments
        cmake_args = ["-GNinja"]
        if install_prefix:
            cmake_args.append(f"-DCMAKE_INSTALL_PREFIX={install_prefix}")
            cmake_args.append(f"-DCMAKE_PREFIX_PATH={install_prefix}")
        cmake_args += pkg.get("cmake_extra_args", [])

        # Escape args for CMake
        cmake_args_str = ";".join(cmake_args)

        # Build command: configure, build, and install in one step.
        # INSTALL_COMMAND "" suppresses the default install step, so install
        # must be part of the build command.
        build_cmd = "cmake --build <BINARY_DIR> --target install"

        lines.append(f"# ExternalProject: {name}")
        lines.append(f"ExternalProject_add({target}")
        lines.append(f"    SOURCE_DIR \"{source_dir}\"")
        lines.append(f"    BINARY_DIR \"{build_dir}/{name}\"")
        lines.append(f"    DOWNLOAD_COMMAND \"\"")
        lines.append(f"    UPDATE_COMMAND \"\"")
        lines.append(f"    CMAKE_ARGS {cmake_args_str}")
        lines.append(f"    BUILD_COMMAND {build_cmd}")
        lines.append(f"    BUILD_ALWAYS TRUE")
        lines.append(f"    INSTALL_COMMAND \"\"")
        lines.append(f"    LOG_CONFIGURE TRUE")
        lines.append(f"    LOG_BUILD TRUE")
        lines.append(f"    LOG_MERGED_STDOUTERR TRUE")
        lines.append(f"    LOG_OUTPUT_ON_FAILURE TRUE")
        if deps_str:
            lines.append(f"    DEPENDS {deps_str}")
        lines.append(f")")
        lines.append("")

    # Top-level ALL target that depends on everything
    all_targets = []
    for name in model.get("topo_order", []):
        pkg = packages[name]
        if pkg.get("type") == "system":
            continue  # system deps are validated separately
        all_targets.append(target_map[name])

    if all_targets:
        lines.append("# Top-level target")
        lines.append(f"add_custom_target(sonicde-all ALL")
        lines.append(f"    DEPENDS {';'.join(all_targets)}")
        lines.append(f")")
        lines.append("")

    out_file.parent.mkdir(parents=True, exist_ok=True)
    out_file.write_text("\n".join(lines))


def generate_dot(model: dict, out_file: Path) -> None:
    """Generate a DOT dependency graph."""
    lines = [
        "digraph SonicDE {",
        "    rankdir=LR;",
        "    nodesep=0.5;",
        "    ranksep=1.0;",
        '    node [shape=box, style=filled, fillcolor=lightyellow, '
        'fontsize=11, fontname="Arial"];',
        '    edge [arrowsize=0.8];',
    ]
    for e in model["edges"]:
        lines.append(f'    "{e["dependent"]}" -> "{e["prerequisite"]}";')
    lines.append("}")
    out_file.write_text("\n".join(lines))


def main(argv: list[str]) -> int:
    import argparse
    ap = argparse.ArgumentParser(description="Generate CMake superbuild")
    ap.add_argument("-model", default="state/model.json")
    ap.add_argument("--cmake-out", default="cmake/SonicDEProjects.cmake")
    ap.add_argument("--dot-out", default="depgraph.dot")
    args = ap.parse_args(argv)

    with open(args.model) as f:
        model = json.load(f)

    generate_cmake(model, Path(args.cmake_out))
    print(f"CMake generated: {args.cmake_out}")
    generate_dot(model, Path(args.dot_out))
    print(f"DOT generated: {args.dot_out}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
